In [1]:
import pandas as pd
import numpy as np
import config

In [ ]:
# Load data
df_com = pd.read_csv("../data/data_communities.csv", index_col=[0])
df = pd.read_csv(config.FEATS_PATH, header=None)
#df_labels = pd.read_csv(config.LABELS_PATH)

In [ ]:
df

,0,1,2,3,4,5,6,7,8,9,...,157,158,159,160,161,162,163,164,165,166
0,230425980,1,-0.171469,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.162097,...,-0.562153,-0.600999,1.461330,1.461369,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792
1,5530458,1,-0.171484,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.162112,...,0.947382,0.673103,-0.979074,-0.978556,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792
2,232022460,1,-0.172107,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.162749,...,0.670883,0.439728,-0.979074,-0.978556,-0.098889,-0.106715,-0.131155,-0.183671,-0.120613,-0.119792
3,232438397,1,0.163054,1.963790,-0.646376,12.409294,-0.063725,9.782742,12.414558,-0.163645,...,-0.577099,-0.613614,0.241128,0.241406,1.072793,0.085530,-0.131155,0.677799,-0.120613,-0.119792
4,230460314,1,1.011523,-0.081127,-1.201369,1.153668,0.333276,1.312656,-0.061584,-0.163523,...,-0.511871,-0.400422,0.517257,0.579382,0.018279,0.277775,0.326394,1.293750,0.178136,0.179117

In [16]:
df_com.head()

,txId,community_id,class,label,n_nodes,n_illicit,n_licit,n_br
0,72646662,0,2,0.0,6553,227.0,1790,0.112543
1,73154569,0,unknown,NaN,6553,227.0,1790,0.112543
2,72630282,0,unknown,NaN,6553,227.0,1790,0.112543
3,73105427,0,unknown,NaN,6553,227.0,1790,0.112543
4,72663059,0,2,0.0,6553,227.0,1790,0.112543